// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\r\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"3","All Restrict":"0","Player Allow":"0","Event Allow":"0","All Allow":"0"}},
{"name":"YEP_GridFreeDoodads","status":true,"description":"v1.06 Place Grid-Free Doodads into your game using an\r\nin-game editor. Static and animated doodads can be used!","parameters":{"---General---":"","Doodads Folder":"img/doodads/","Doodads Smoothing":"false","Alphabetical Settings":"false","---Grid Snap---":"","Default Grid Snap":"false","Grid Snap Width":"48","Grid Snap Height":"48"}}
];
